### ISSUE TITLE
SyntaxError: Unexpected token => running on node v0.12.9

### ISSUE THREAD

**Issue by victorbstan** [UsamaAshraf/node-packages#1]
```
node_modules/node-cron-job/lib/runner.js:24
    ps.on('close', (code) => {
                          ^^

SyntaxError: Unexpected token =>
```

**Comment by UsamaAshraf** [comment]
@victorbstan I think you should update your node version to 4.x.x (which will also mean updating to ES6 for javascript). This will allow the token '=>' (arrow function expression).

If you're curious [(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)]
